### ISSUE TITLE
Did not rendering area

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-mapnik#66] opened 2019-03-01 13:27 UTC
Two days ago I found a strip on map that doesnt have rendering on zoom 15 and more.
Here is the area https://www.freemap.sk/?map=15/48.610441/17.957282&layers=X

**Comment by zdila** [comment] 2019-03-01 13:28
Duplicate of #54

**Closed by zdila** 2019-03-01 13:28 UTC
